apiVersion: v1
kind: config

clusters:
-  cluster:
	server: https://192.168.99.100:8443
	certificate-authority: /root/ca.crt
   name: mycluster

contexts:
-  context:
     cluster: mycluster
     user: admin

users:
-  name: admin
   user:
     client-key: /root/client.key
     client-certificate: /root/client.crt